# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grsp_project.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13postgres_test.proto\x12\x16\x63om.postgtrs_test.grpc\"<\n\x0eGetDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\";\n\rGetDatatReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"d\n\x0eSetDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x10\n\x08new_name\x18\x04 \x01(\t\x12\x14\n\x0cnew_quantity\x18\x05 \x01(\x05\"\x1e\n\x0cSetDataReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xae\x02\n\x07GetData\x12_\n\x0cSelectByName\x12&.com.postgtrs_test.grpc.GetDataRequest\x1a%.com.postgtrs_test.grpc.GetDatatReply\"\x00\x12]\n\nSelectByID\x12&.com.postgtrs_test.grpc.GetDataRequest\x1a%.com.postgtrs_test.grpc.GetDatatReply\"\x00\x12\x63\n\x10SelectByQuantity\x12&.com.postgtrs_test.grpc.GetDataRequest\x1a%.com.postgtrs_test.grpc.GetDatatReply\"\x00\x32\xbd\x01\n\x07SetData\x12X\n\x06Insert\x12&.com.postgtrs_test.grpc.SetDataRequest\x1a$.com.postgtrs_test.grpc.SetDataReply\"\x00\x12X\n\x06Update\x12&.com.postgtrs_test.grpc.SetDataRequest\x1a$.com.postgtrs_test.grpc.SetDataReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'postgres_test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETDATAREQUEST']._serialized_start=47
  _globals['_GETDATAREQUEST']._serialized_end=107
  _globals['_GETDATATREPLY']._serialized_start=109
  _globals['_GETDATATREPLY']._serialized_end=168
  _globals['_SETDATAREQUEST']._serialized_start=170
  _globals['_SETDATAREQUEST']._serialized_end=270
  _globals['_SETDATAREPLY']._serialized_start=272
  _globals['_SETDATAREPLY']._serialized_end=302
  _globals['_GETDATA']._serialized_start=305
  _globals['_GETDATA']._serialized_end=607
  _globals['_SETDATA']._serialized_start=610
  _globals['_SETDATA']._serialized_end=799
# @@protoc_insertion_point(module_scope)
